<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up()
    {
        DB::table('racas')->insert([
            ['nome' => 'Affenpinscher', 'especie_id' => '1'],
            ['nome' => 'Afghan Hound', 'especie_id' => '1'],
            ['nome' => 'Airedale Terrier', 'especie_id' => '1'],
            ['nome' => 'Akbash', 'especie_id' => '1'],
            ['nome' => 'Akita Americano', 'especie_id' => '1'],
            ['nome' => 'Akita Inu', 'especie_id' => '1'],
            ['nome' => 'American Bully', 'especie_id' => '1'],
            ['nome' => 'American Staffordshire Terrier', 'especie_id' => '1'],
            ['nome' => 'Australian Cattle Dog', 'especie_id' => '1'],
            ['nome' => 'Azawakh', 'especie_id' => '1'],
            ['nome' => 'Barbet', 'especie_id' => '1'],
            ['nome' => 'Basenji', 'especie_id' => '1'],
            ['nome' => 'Basset Alpino', 'especie_id' => '1'],
            ['nome' => 'Basset Artesiano Normando', 'especie_id' => '1'],
            ['nome' => 'Basset de Vestfália', 'especie_id' => '1'],
            ['nome' => 'Basset fulvo da bretanha', 'especie_id' => '1'],
            ['nome' => 'Basset Hound', 'especie_id' => '1'],
            ['nome' => 'Beagle', 'especie_id' => '1'],
            ['nome' => 'Beagle Harrier', 'especie_id' => '1'],
            ['nome' => 'Bearded Collie', 'especie_id' => '1'],
            ['nome' => 'Bedlington Terrier', 'especie_id' => '1'],
            ['nome' => 'Bernese Mountain Dog', 'especie_id' => '1'],
            ['nome' => 'Bichon Bolonhês', 'especie_id' => '1'],
            ['nome' => 'Bichon Frisé', 'especie_id' => '1'],
            ['nome' => 'Bichon Havanês', 'especie_id' => '1'],
            ['nome' => 'Biewer Terrier', 'especie_id' => '1'],
            ['nome' => 'Billy', 'especie_id' => '1'],
            ['nome' => 'Bloodhound', 'especie_id' => '1'],
            ['nome' => 'Boerboel', 'especie_id' => '1'],
            ['nome' => 'Boiadeiro de Appenzel', 'especie_id' => '1'],
            ['nome' => 'Boiadeiro de Entlebuch', 'especie_id' => '1'],
            ['nome' => 'Boiadeiro de Flandres', 'especie_id' => '1'],
            ['nome' => 'Border Collie', 'especie_id' => '1'],
            ['nome' => 'Border Terrier', 'especie_id' => '1'],
            ['nome' => 'Borzói', 'especie_id' => '1'],
            ['nome' => 'Boston Terrier', 'especie_id' => '1'],
            ['nome' => 'Boxer', 'especie_id' => '1'],
            ['nome' => 'Braco Alemão de Pêlo Curto', 'especie_id' => '1'],
            ['nome' => 'Braco de Auvergne', 'especie_id' => '1'],
            ['nome' => 'Braco de Bourbon', 'especie_id' => '1'],
            ['nome' => 'Braco Italiano', 'especie_id' => '1'],
            ['nome' => 'Buhund Norueguês', 'especie_id' => '1'],
            ['nome' => 'Buldogue Americano', 'especie_id' => '1'],
            ['nome' => 'Buldogue Campeiro', 'especie_id' => '1'],
            ['nome' => 'Buldogue inglês', 'especie_id' => '1'],
            ['nome' => 'Buldogue Serrano', 'especie_id' => '1'],
            ['nome' => 'Bull Terrier', 'especie_id' => '1'],
            ['nome' => 'Bull Terrier Miniatura', 'especie_id' => '1'],
            ['nome' => 'Bulldog Francês', 'especie_id' => '1'],
            ['nome' => 'Bullmastiff', 'especie_id' => '1'],
            ['nome' => 'Cairn Terrier', 'especie_id' => '1'],
            ['nome' => 'Cane Corso', 'especie_id' => '1'],
            ['nome' => 'Cão D\'água Frisado', 'especie_id' => '1'],
            ['nome' => 'Cão D\'água Português', 'especie_id' => '1'],
            ['nome' => 'Cão da Eurásia', 'especie_id' => '1'],
            ['nome' => 'Cão da Groenlândia', 'especie_id' => '1'],
            ['nome' => 'Cão da Serra da Estrela', 'especie_id' => '1'],
            ['nome' => 'Cão das Montanhas do Atlas', 'especie_id' => '1'],
            ['nome' => 'Cão de Canãa', 'especie_id' => '1'],
            ['nome' => 'Cão de Castro Laboreiro', 'especie_id' => '1'],
            ['nome' => 'Cão de Crista Chinês', 'especie_id' => '1'],
            ['nome' => 'Cão do Faraó', 'especie_id' => '1'],
            ['nome' => 'Cão dos Pirineus', 'especie_id' => '1'],
            ['nome' => 'Cão D’água Espanhol', 'especie_id' => '1'],
            ['nome' => 'Cão Lobo Tchecoslovaco', 'especie_id' => '1'],
            ['nome' => 'Cavalier King Charles Spaniel', 'especie_id' => '1'],
            ['nome' => 'Cesky Fousek', 'especie_id' => '1'],
            ['nome' => 'Cesky Terrier', 'especie_id' => '1'],
            ['nome' => 'Chihuahua', 'especie_id' => '1'],
            ['nome' => 'Chow Chow', 'especie_id' => '1'],
            ['nome' => 'Cimarrón Uruguayo', 'especie_id' => '1'],
            ['nome' => 'Clumber', 'especie_id' => '1'],
            ['nome' => 'Cocker Spaniel Americano', 'especie_id' => '1'],
            ['nome' => 'Cocker Spaniel Inglês', 'especie_id' => '1'],
            ['nome' => 'Collie', 'especie_id' => '1'],
            ['nome' => 'Collie Pelo Curto (Smooth Collie)', 'especie_id' => '1'],
            ['nome' => 'Coonhound Preto E Castanho', 'especie_id' => '1'],
            ['nome' => 'Coton de Tulear', 'especie_id' => '1'],
            ['nome' => 'Dachshund', 'especie_id' => '1'],
            ['nome' => 'Dálmata', 'especie_id' => '1'],
            ['nome' => 'Dandie Dinmont Terrier', 'especie_id' => '1'],
            ['nome' => 'Deerhound', 'especie_id' => '1'],
            ['nome' => 'Doberman', 'especie_id' => '1'],
            ['nome' => 'Dogo Argentino', 'especie_id' => '1'],
            ['nome' => 'Dogo Canário', 'especie_id' => '1'],
            ['nome' => 'Dogue Alemão', 'especie_id' => '1'],
            ['nome' => 'Dogue Brasileiro', 'especie_id' => '1'],
            ['nome' => 'Dogue de Bordeaux', 'especie_id' => '1'],
            ['nome' => 'Dunker Norueguês', 'especie_id' => '1'],
            ['nome' => 'Elkhound', 'especie_id' => '1'],
            ['nome' => 'Fila Brasileiro', 'especie_id' => '1'],
            ['nome' => 'Flat Coated Retriever', 'especie_id' => '1'],
            ['nome' => 'Fox Terrier', 'especie_id' => '1'],
            ['nome' => 'Fox Terrier Pelo Liso', 'especie_id' => '1'],
            ['nome' => 'Foxhound Americano', 'especie_id' => '1'],
            ['nome' => 'Foxhound Inglês', 'especie_id' => '1'],
            ['nome' => 'Galgo Escocês', 'especie_id' => '1'],
            ['nome' => 'Galgo Espanhol', 'especie_id' => '1'],
            ['nome' => 'Gascão de Saintongeois', 'especie_id' => '1'],
            ['nome' => 'Golden Retriever', 'especie_id' => '1'],
            ['nome' => 'Greyhound', 'especie_id' => '1'],
            ['nome' => 'Griffon Azul da Gasconha', 'especie_id' => '1'],
            ['nome' => 'Griffon de Bruxelas', 'especie_id' => '1'],
            ['nome' => 'Griffon de Nivernais', 'especie_id' => '1'],
            ['nome' => 'Husky Siberiano', 'especie_id' => '1'],
            ['nome' => 'Irish Soft Coated Wheaten Terrier', 'especie_id' => '1'],
            ['nome' => 'Irish Wolfhound', 'especie_id' => '1'],
            ['nome' => 'Jack Russell Terrier', 'especie_id' => '1'],
            ['nome' => 'Keeshond (Wolfspitz)', 'especie_id' => '1'],
            ['nome' => 'Kelpie', 'especie_id' => '1'],
            ['nome' => 'Kerry Blue Terrier', 'especie_id' => '1'],
            ['nome' => 'Komondor', 'especie_id' => '1'],
            ['nome' => 'Korea Jindo Dog', 'especie_id' => '1'],
            ['nome' => 'Kromfohrlander', 'especie_id' => '1'],
            ['nome' => 'Kuvasz', 'especie_id' => '1'],
            ['nome' => 'Labrador Retriever', 'especie_id' => '1'],
            ['nome' => 'Lagotto Romagnolo', 'especie_id' => '1'],
            ['nome' => 'Laika da Sibéria Ocidental', 'especie_id' => '1'],
            ['nome' => 'Lakeland Terrier', 'especie_id' => '1'],
            ['nome' => 'Leonberger', 'especie_id' => '1'],
            ['nome' => 'Lhasa Apso', 'especie_id' => '1'],
            ['nome' => 'Malamute do Alasca', 'especie_id' => '1'],
            ['nome' => 'Maltês', 'especie_id' => '1'],
            ['nome' => 'Manchester Terrier', 'especie_id' => '1'],
            ['nome' => 'Mastiff', 'especie_id' => '1'],
            ['nome' => 'Mastim Dos Pirineus', 'especie_id' => '1'],
            ['nome' => 'Mastim Espanhol', 'especie_id' => '1'],
            ['nome' => 'Mastim Napolitano', 'especie_id' => '1'],
            ['nome' => 'Mastim Tibetano', 'especie_id' => '1'],
            ['nome' => 'Mudi', 'especie_id' => '1'],
            ['nome' => 'Norfolk Terrier', 'especie_id' => '1'],
            ['nome' => 'Norwich Terrier', 'especie_id' => '1'],
            ['nome' => 'Old English Sheepdog', 'especie_id' => '1'],
            ['nome' => 'Oscar A. Melo', 'especie_id' => '1'],
            ['nome' => 'Otterhound', 'especie_id' => '1'],
            ['nome' => 'Papillon', 'especie_id' => '1'],
            ['nome' => 'Pastor Alemão', 'especie_id' => '1'],
            ['nome' => 'Pastor Australiano', 'especie_id' => '1'],
            ['nome' => 'Pastor Belga Groenendael', 'especie_id' => '1'],
            ['nome' => 'Pastor Belga Laekenois', 'especie_id' => '1'],
            ['nome' => 'Pastor Belga Malinois', 'especie_id' => '1'],
            ['nome' => 'Pastor Belga Tervuren', 'especie_id' => '1'],
            ['nome' => 'Pastor Bergamo', 'especie_id' => '1'],
            ['nome' => 'Pastor branco suíço', 'especie_id' => '1'],
            ['nome' => 'Pastor da Anatólia', 'especie_id' => '1'],
            ['nome' => 'Pastor da Ásia Central', 'especie_id' => '1'],
            ['nome' => 'Pastor de Beauce', 'especie_id' => '1'],
            ['nome' => 'Pastor de Brie', 'especie_id' => '1'],
            ['nome' => 'Pastor de Shetland', 'especie_id' => '1'],
            ['nome' => 'Pastor do Cáucaso', 'especie_id' => '1'],
            ['nome' => 'Pastor Finlandês da Lapônia', 'especie_id' => '1'],
            ['nome' => 'Pastor Holandês', 'especie_id' => '1'],
            ['nome' => 'Pastor Iugoslavo', 'especie_id' => '1'],
            ['nome' => 'Pastor Maremano Abruzês', 'especie_id' => '1'],
            ['nome' => 'Pastor Polonês da Planície', 'especie_id' => '1'],
            ['nome' => 'Pelado Mexicano', 'especie_id' => '1'],
            ['nome' => 'Pequeno Cão Leão', 'especie_id' => '1'],
            ['nome' => 'Pequeno Galgo Italiano', 'especie_id' => '1'],
            ['nome' => 'Pequeno Lebrel Italiano (Greyhound Italiano)', 'especie_id' => '1'],
            ['nome' => 'Pequeno Spaniel Continental', 'especie_id' => '1'],
            ['nome' => 'Pequinês', 'especie_id' => '1'],
            ['nome' => 'Perdigueiro Português', 'especie_id' => '1'],
            ['nome' => 'Petit Basset Griffon Vendéen', 'especie_id' => '1'],
            ['nome' => 'Pinscher', 'especie_id' => '1'],
            ['nome' => 'Pitbull', 'especie_id' => '1'],
            ['nome' => 'Podengo Canário', 'especie_id' => '1'],
            ['nome' => 'Podengo Ibicenco', 'especie_id' => '1'],
            ['nome' => 'Podengo Português', 'especie_id' => '1'],
            ['nome' => 'Pointer inglês', 'especie_id' => '1'],
            ['nome' => 'Poodle', 'especie_id' => '1'],
            ['nome' => 'Poodle Gigante', 'especie_id' => '1'],
            ['nome' => 'Pudelpointer', 'especie_id' => '1'],
            ['nome' => 'Pug', 'especie_id' => '1'],
            ['nome' => 'Pumi', 'especie_id' => '1'],
            ['nome' => 'Rafeiro do Alentejo', 'especie_id' => '1'],
            ['nome' => 'Retriever da Baía de Chesapeake', 'especie_id' => '1'],
            ['nome' => 'Retriever da Nova Escócia', 'especie_id' => '1'],
            ['nome' => 'Rodhesian Ridgeback', 'especie_id' => '1'],
            ['nome' => 'Rottweiler', 'especie_id' => '1'],
            ['nome' => 'Saluki', 'especie_id' => '1'],
            ['nome' => 'Samoieda', 'especie_id' => '1'],
            ['nome' => 'São Bernardo', 'especie_id' => '1'],
            ['nome' => 'Schipperke', 'especie_id' => '1'],
            ['nome' => 'Schnauzer', 'especie_id' => '1'],
            ['nome' => 'Schnauzer gigante', 'especie_id' => '1'],
            ['nome' => 'Scottish Terrier', 'especie_id' => '1'],
            ['nome' => 'Setter Gordon', 'especie_id' => '1'],
            ['nome' => 'Setter Inglês', 'especie_id' => '1'],
            ['nome' => 'Setter Irlandês', 'especie_id' => '1'],
            ['nome' => 'Setter Irlandês vermelho e branco', 'especie_id' => '1'],
            ['nome' => 'SharPei', 'especie_id' => '1'],
            ['nome' => 'Shiba', 'especie_id' => '1'],
            ['nome' => 'Shih Tzu', 'especie_id' => '1'],
            ['nome' => 'Silky Terrier Australiano', 'especie_id' => '1'],
            ['nome' => 'Skye Terrier', 'especie_id' => '1'],
            ['nome' => 'Sloughi (Galgo Árabe)', 'especie_id' => '1'],
            ['nome' => 'Spaniel Bretão', 'especie_id' => '1'],
            ['nome' => 'Spaniel D’água Americano', 'especie_id' => '1'],
            ['nome' => 'Spaniel D’água Irlandês', 'especie_id' => '1'],
            ['nome' => 'Spaniel Francês', 'especie_id' => '1'],
            ['nome' => 'Spaniel Japonês', 'especie_id' => '1'],
            ['nome' => 'Spaniel Tibetano', 'especie_id' => '1'],
            ['nome' => 'Spinone Italiano', 'especie_id' => '1'],
            ['nome' => 'Spitz Alemão', 'especie_id' => '1'],
            ['nome' => 'Spitz Finlandês', 'especie_id' => '1'],
            ['nome' => 'Spitz Japonês', 'especie_id' => '1'],
            ['nome' => 'Springer Spaniel Inglês', 'especie_id' => '1'],
            ['nome' => 'Staffordshire Bull Terrier', 'especie_id' => '1'],
            ['nome' => 'TerraNova', 'especie_id' => '1'],
            ['nome' => 'Terrier Australiano', 'especie_id' => '1'],
            ['nome' => 'Terrier Brasileiro', 'especie_id' => '1'],
            ['nome' => 'Terrier Irlandês', 'especie_id' => '1'],
            ['nome' => 'Terrier Tibetano', 'especie_id' => '1'],
            ['nome' => 'Thai Ridgeback', 'especie_id' => '1'],
            ['nome' => 'Tosa', 'especie_id' => '1'],
            ['nome' => 'Veadeiro Pampeano', 'especie_id' => '1'],
            ['nome' => 'Vira Lata (SRD)', 'especie_id' => '1'],
            ['nome' => 'Vizsla Húngaro', 'especie_id' => '1'],
            ['nome' => 'Volpino Italiano', 'especie_id' => '1'],
            ['nome' => 'Weimaraner', 'especie_id' => '1'],
            ['nome' => 'Welsh Corgi Cardigan e Welsh Corgi Pembroke', 'especie_id' => '1'],
            ['nome' => 'Welsh Terrier', 'especie_id' => '1'],
            ['nome' => 'West Highland White Terrier', 'especie_id' => '1'],
            ['nome' => 'Whippet', 'especie_id' => '1'],
            ['nome' => 'Yorkshire Terrier', 'especie_id' => '1'],
            ['nome' => 'Abissínio', 'especie_id' => '2'],
            ['nome' => 'American Bobtail', 'especie_id' => '2'],
            ['nome' => 'American Curl', 'especie_id' => '2'],
            ['nome' => 'American Shorthair', 'especie_id' => '2'],
            ['nome' => 'American Wirehair', 'especie_id' => '2'],
            ['nome' => 'Balinês', 'especie_id' => '2'],
            ['nome' => 'Bengal', 'especie_id' => '2'],
            ['nome' => 'Birmanês', 'especie_id' => '2'],
            ['nome' => 'Bombay', 'especie_id' => '2'],
            ['nome' => 'British Shorthair', 'especie_id' => '2'],
            ['nome' => 'Burmese', 'especie_id' => '2'],
            ['nome' => 'Burmilla', 'especie_id' => '2'],
            ['nome' => 'Chartreux', 'especie_id' => '2'],
            ['nome' => 'Cornish Rex', 'especie_id' => '2'],
            ['nome' => 'Devon Rex', 'especie_id' => '2'],
            ['nome' => 'Egyptian Mau', 'especie_id' => '2'],
            ['nome' => 'Exótico', 'especie_id' => '2'],
            ['nome' => 'Gato doméstico de pelo curto', 'especie_id' => '2'],
            ['nome' => 'Gato doméstico de pelo longo', 'especie_id' => '2'],
            ['nome' => 'Gato doméstico de pelo médio', 'especie_id' => '2'],
            ['nome' => 'Havana Brown', 'especie_id' => '2'],
            ['nome' => 'Himalaio', 'especie_id' => '2'],
            ['nome' => 'Japanese Bobtail', 'especie_id' => '2'],
            ['nome' => 'Javanese', 'especie_id' => '2'],
            ['nome' => 'Korat', 'especie_id' => '2'],
            ['nome' => 'LaPerm', 'especie_id' => '2'],
            ['nome' => 'Maine Coon', 'especie_id' => '2'],
            ['nome' => 'Manx', 'especie_id' => '2'],
            ['nome' => 'Munchkin', 'especie_id' => '2'],
            ['nome' => 'Nebelung', 'especie_id' => '2'],
            ['nome' => 'Norueguês da Floresta', 'especie_id' => '2'],
            ['nome' => 'Ocicat', 'especie_id' => '2'],
            ['nome' => 'Oriental', 'especie_id' => '2'],
            ['nome' => 'Persa', 'especie_id' => '2'],
            ['nome' => 'Peterbald', 'especie_id' => '2'],
            ['nome' => 'Ragdoll', 'especie_id' => '2'],
            ['nome' => 'Russian Blue', 'especie_id' => '2'],
            ['nome' => 'Scottish Fold', 'especie_id' => '2'],
            ['nome' => 'Selkirk Rex', 'especie_id' => '2'],
            ['nome' => 'Siamese', 'especie_id' => '2'],
            ['nome' => 'Siberian', 'especie_id' => '2'],
            ['nome' => 'Singapura', 'especie_id' => '2'],
            ['nome' => 'Snowshoe', 'especie_id' => '2'],
            ['nome' => 'Somali', 'especie_id' => '2'],
            ['nome' => 'Sphynx', 'especie_id' => '2'],
            ['nome' => 'Tonquinês', 'especie_id' => '2'],
            ['nome' => 'Turkish Angora', 'especie_id' => '2'],
            ['nome' => 'Turkish Van', 'especie_id' => '2'],
            ['nome' => 'Vira Lata (SRD)', 'especie_id' => '2']
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        //
    }
};
