<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        DB::table('racas')->insert(
            array(
                ['nome' => 'Affenpinscher'],
                ['nome' => 'Afghan Hound'],
                ['nome' => 'Airedale Terrier'],
                ['nome' => 'Akbash'],
                ['nome' => 'Akita Americano'],
                ['nome' => 'Akita Inu'],
                ['nome' => 'American Bully'],
                ['nome' => 'American Staffordshire Terrier'],
                ['nome' => 'Australian Cattle Dog'],
                ['nome' => 'Azawakh'],
                ['nome' => 'Barbet'],
                ['nome' => 'Basenji'],
                ['nome' => 'Basset Alpino'],
                ['nome' => 'Basset Artesiano Normando'],
                ['nome' => 'Basset de Vestfália'],
                ['nome' => 'Basset fulvo da bretanha'],
                ['nome' => 'Basset Hound'],
                ['nome' => 'Beagle'],
                ['nome' => 'Beagle Harrier'],
                ['nome' => 'Bearded Collie'],
                ['nome' => 'Bedlington Terrier'],
                ['nome' => 'Bernese Mountain Dog'],
                ['nome' => 'Bichon Bolonhês'],
                ['nome' => 'Bichon Frisé'],
                ['nome' => 'Bichon Havanês'],
                ['nome' => 'Biewer Terrier'],
                ['nome' => 'Billy'],
                ['nome' => 'Bloodhound'],
                ['nome' => 'Boerboel'],
                ['nome' => 'Boiadeiro de Appenzel'],
                ['nome' => 'Boiadeiro de Entlebuch'],
                ['nome' => 'Boiadeiro de Flandres'],
                ['nome' => 'Border Collie'],
                ['nome' => 'Border Terrier'],
                ['nome' => 'Borzói'],
                ['nome' => 'Boston Terrier'],
                ['nome' => 'Boxer'],
                ['nome' => 'Braco Alemão de Pêlo Curto'],
                ['nome' => 'Braco de Auvergne'],
                ['nome' => 'Braco de Bourbon'],
                ['nome' => 'Braco Italiano'],
                ['nome' => 'Buhund Norueguês'],
                ['nome' => 'Buldogue Americano'],
                ['nome' => 'Buldogue Campeiro'],
                ['nome' => 'Buldogue inglês'],
                ['nome' => 'Buldogue Serrano'],
                ['nome' => 'Bull Terrier'],
                ['nome' => 'Bull Terrier Miniatura'],
                ['nome' => 'Bulldog Francês'],
                ['nome' => 'Bullmastiff'],
                ['nome' => 'Cairn Terrier'],
                ['nome' => 'Cane Corso'],
                ['nome' => 'Cão D\'água Frisado'],
                ['nome' => 'Cão D\'água Português'],
                ['nome' => 'Cão da Eurásia'],
                ['nome' => 'Cão da Groenlândia'],
                ['nome' => 'Cão da Serra da Estrela'],
                ['nome' => 'Cão das Montanhas do Atlas'],
                ['nome' => 'Cão de Canãa'],
                ['nome' => 'Cão de Castro Laboreiro'],
                ['nome' => 'Cão de Crista Chinês'],
                ['nome' => 'Cão do Faraó'],
                ['nome' => 'Cão dos Pirineus'],
                ['nome' => 'Cão D’água Espanhol'],
                ['nome' => 'Cão Lobo Tchecoslovaco'],
                ['nome' => 'Cavalier King Charles Spaniel'],
                ['nome' => 'Cesky Fousek'],
                ['nome' => 'Cesky Terrier'],
                ['nome' => 'Chihuahua'],
                ['nome' => 'Chow Chow'],
                ['nome' => 'Cimarrón Uruguayo'],
                ['nome' => 'Clumber'],
                ['nome' => 'Cocker Spaniel Americano'],
                ['nome' => 'Cocker Spaniel Inglês'],
                ['nome' => 'Collie'],
                ['nome' => 'Collie Pelo Curto (Smooth Collie)'],
                ['nome' => 'Coonhound Preto E Castanho'],
                ['nome' => 'Coton de Tulear'],
                ['nome' => 'Dachshund'],
                ['nome' => 'Dálmata'],
                ['nome' => 'Dandie Dinmont Terrier'],
                ['nome' => 'Deerhound'],
                ['nome' => 'Doberman'],
                ['nome' => 'Dogo Argentino'],
                ['nome' => 'Dogo Canário'],
                ['nome' => 'Dogue Alemão'],
                ['nome' => 'Dogue Brasileiro'],
                ['nome' => 'Dogue de Bordeaux'],
                ['nome' => 'Dunker Norueguês'],
                ['nome' => 'Elkhound'],
                ['nome' => 'Fila Brasileiro'],
                ['nome' => 'Flat Coated Retriever'],
                ['nome' => 'Fox Terrier'],
                ['nome' => 'Fox Terrier Pelo Liso'],
                ['nome' => 'Foxhound Americano'],
                ['nome' => 'Foxhound Inglês'],
                ['nome' => 'Galgo Escocês'],
                ['nome' => 'Galgo Espanhol'],
                ['nome' => 'Gascão de Saintongeois'],
                ['nome' => 'Golden Retriever'],
                ['nome' => 'Greyhound'],
                ['nome' => 'Griffon Azul da Gasconha'],
                ['nome' => 'Griffon de Bruxelas'],
                ['nome' => 'Griffon de Nivernais'],
                ['nome' => 'Husky Siberiano'],
                ['nome' => 'Irish Soft Coated Wheaten Terrier'],
                ['nome' => 'Irish Wolfhound'],
                ['nome' => 'Jack Russell Terrier'],
                ['nome' => 'Keeshond (Wolfspitz)'],
                ['nome' => 'Kelpie'],
                ['nome' => 'Kerry Blue Terrier'],
                ['nome' => 'Komondor'],
                ['nome' => 'Korea Jindo Dog'],
                ['nome' => 'Kromfohrlander'],
                ['nome' => 'Kuvasz'],
                ['nome' => 'Labrador Retriever'],
                ['nome' => 'Lagotto Romagnolo'],
                ['nome' => 'Laika da Sibéria Ocidental'],
                ['nome' => 'Lakeland Terrier'],
                ['nome' => 'Leonberger'],
                ['nome' => 'Lhasa Apso'],
                ['nome' => 'Malamute do Alasca'],
                ['nome' => 'Maltês'],
                ['nome' => 'Manchester Terrier'],
                ['nome' => 'Mastiff'],
                ['nome' => 'Mastim Dos Pirineus'],
                ['nome' => 'Mastim Espanhol'],
                ['nome' => 'Mastim Napolitano'],
                ['nome' => 'Mastim Tibetano'],
                ['nome' => 'Mudi'],
                ['nome' => 'Norfolk Terrier'],
                ['nome' => 'Norwich Terrier'],
                ['nome' => 'Old English Sheepdog'],
                ['nome' => 'Oscar A. Melo'],
                ['nome' => 'Otterhound'],
                ['nome' => 'Papillon'],
                ['nome' => 'Pastor Alemão'],
                ['nome' => 'Pastor Australiano'],
                ['nome' => 'Pastor Belga Groenendael'],
                ['nome' => 'Pastor Belga Laekenois'],
                ['nome' => 'Pastor Belga Malinois'],
                ['nome' => 'Pastor Belga Tervuren'],
                ['nome' => 'Pastor Bergamo'],
                ['nome' => 'Pastor branco suíço'],
                ['nome' => 'Pastor da Anatólia'],
                ['nome' => 'Pastor da Ásia Central'],
                ['nome' => 'Pastor de Beauce'],
                ['nome' => 'Pastor de Brie'],
                ['nome' => 'Pastor de Shetland'],
                ['nome' => 'Pastor do Cáucaso'],
                ['nome' => 'Pastor Finlandês da Lapônia'],
                ['nome' => 'Pastor Holandês'],
                ['nome' => 'Pastor Iugoslavo'],
                ['nome' => 'Pastor Maremano Abruzês'],
                ['nome' => 'Pastor Polonês da Planície'],
                ['nome' => 'Pelado Mexicano'],
                ['nome' => 'Pequeno Cão Leão'],
                ['nome' => 'Pequeno Galgo Italiano'],
                ['nome' => 'Pequeno Lebrel Italiano (Greyhound Italiano)'],
                ['nome' => 'Pequeno Spaniel Continental'],
                ['nome' => 'Pequinês'],
                ['nome' => 'Perdigueiro Português'],
                ['nome' => 'Petit Basset Griffon Vendéen'],
                ['nome' => 'Pinscher'],
                ['nome' => 'Pitbull'],
                ['nome' => 'Podengo Canário'],
                ['nome' => 'Podengo Ibicenco'],
                ['nome' => 'Podengo Português'],
                ['nome' => 'Pointer inglês'],
                ['nome' => 'Poodle'],
                ['nome' => 'Poodle Gigante'],
                ['nome' => 'Pudelpointer'],
                ['nome' => 'Pug'],
                ['nome' => 'Pumi'],
                ['nome' => 'Rafeiro do Alentejo'],
                ['nome' => 'Retriever da Baía de Chesapeake'],
                ['nome' => 'Retriever da Nova Escócia'],
                ['nome' => 'Rodhesian Ridgeback'],
                ['nome' => 'Rottweiler'],
                ['nome' => 'Saluki'],
                ['nome' => 'Samoieda'],
                ['nome' => 'São Bernardo'],
                ['nome' => 'Schipperke'],
                ['nome' => 'Schnauzer'],
                ['nome' => 'Schnauzer gigante'],
                ['nome' => 'Scottish Terrier'],
                ['nome' => 'Setter Gordon'],
                ['nome' => 'Setter Inglês'],
                ['nome' => 'Setter Irlandês'],
                ['nome' => 'Setter Irlandês vermelho e branco'],
                ['nome' => 'SharPei'],
                ['nome' => 'Shiba'],
                ['nome' => 'Shih Tzu'],
                ['nome' => 'Silky Terrier Australiano'],
                ['nome' => 'Skye Terrier'],
                ['nome' => 'Sloughi (Galgo Árabe)'],
                ['nome' => 'Spaniel Bretão'],
                ['nome' => 'Spaniel D’água Americano'],
                ['nome' => 'Spaniel D’água Irlandês'],
                ['nome' => 'Spaniel Francês'],
                ['nome' => 'Spaniel Japonês'],
                ['nome' => 'Spaniel Tibetano'],
                ['nome' => 'Spinone Italiano'],
                ['nome' => 'Spitz Alemão'],
                ['nome' => 'Spitz Finlandês'],
                ['nome' => 'Spitz Japonês'],
                ['nome' => 'Springer Spaniel Inglês'],
                ['nome' => 'Staffordshire Bull Terrier'],
                ['nome' => 'TerraNova'],
                ['nome' => 'Terrier Australiano'],
                ['nome' => 'Terrier Brasileiro'],
                ['nome' => 'Terrier Irlandês'],
                ['nome' => 'Terrier Tibetano'],
                ['nome' => 'Thai Ridgeback'],
                ['nome' => 'Tosa'],
                ['nome' => 'Veadeiro Pampeano'],
                ['nome' => 'Vira Lata (SRD)'],
                ['nome' => 'Vizsla Húngaro'],
                ['nome' => 'Volpino Italiano'],
                ['nome' => 'Weimaraner'],
                ['nome' => 'Welsh Corgi Cardigan e Welsh Corgi Pembroke'],
                ['nome' => 'Welsh Terrier'],
                ['nome' => 'West Highland White Terrier'],
                ['nome' => 'Whippet'],
                ['nome' => 'Yorkshire Terrier'],
            )
        );
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        //
    }
};
